### PR TITLE
Updates Dropzone to its 4.0.0 version

### PR DESCRIPTION
**Pull request by ncuesta**
Also changes the logic of the Rakefile to adapt itself to the changes introduced in the library's dist code layout.

### CODE REVIEW

**Comment by Dinuz** [comment]
@ncuesta absolutely!

I am going to do it in a couple of hours...ok?

**Comment by ncuesta** [comment]
@Dinuz great! Didn't expect such a timely response, so take your time :bow:

**Comment by Dinuz** [comment]
@ncuesta are we in the same side of the world? lol

**Comment by Dinuz** [comment]
@ncuesta well I tested the branch, and it seems working fine.
I mean i bundle install it without any issue and I just include js and scss with @import without problem.

I need to say I didn't use yet the code (as I didn't use the library at all...I am tweaking some backend image processing on my app, and I should be able to pull out the front end I believe tomorrow).

If you want that I fully test also the js please wait another couple of days before merging.

I don't think there should be problems anyway, just because your gem only bring the dropzone assets in the pipeline. If any issue probably that it's just related with the library.

**Comment by ncuesta** [comment]
Awesome @Dinuz! Thanks for being the guinea pig for this release :)

I'll merge it in, and if anything should fail, we'll fix it on 0.7.1.

Kudos to you!

**Pull request merged**
